[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings=['aave-v3-core/=lib/aave-v3-core/','gho-core/=lib/gho-core/','@openzeppelin/=lib/openzeppelin-contracts/']


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"